### ISSUE TITLE
 Cannot read property 'bucket' of undefined

### ISSUE THREAD

**Issue by sunkhanna** [bypasslane/sftp-to-s3#16]
Hi I am getting the error

Error TypeError: Cannot read property 'bucket' of undefined
    at Promise.all.files.map.file (/var/task/node_modules/sftp-to-s3/lib/uploadToS3.js:13:30)
    at Array.map (<anonymous>)
    at Object.putBatch (/var/task/node_modules/sftp-to-s3/lib/uploadToS3.js:10:11)
    at sftp.connect.then.then.then.then.dataArray (/var/task/node_modules/sftp-to-s3/index.js:51:29)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
2019-01-08T09:54:48.628Z	6e64ec46-132b-11e9-b3c3-db42be5d20c8	TypeError: Cannot read property 'bucket' of undefined
    at Promise.all.files.map.file (/var/task/node_modules/sftp-to-s3/lib/uploadToS3.js:13:30)
    at Array.map (<anonymous>)
    at Object.putBatch (/var/task/node_modules/sftp-to-s3/lib/uploadToS3.js:10:11)
    at sftp.connect.then.then.then.then.dataArray (/var/task/node_modules/sftp-to-s3/index.js:51:29)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

I am also looking into it,not sure why its coming.

In putbatch function I am getting the complete config object.

Below is my code:

const SftpToS3 = require("sftp-to-s3");
var fs = require("fs");

config = {
  sftp: {
    host: "176.36.86.66",
    username: "ubuntu",
    //  password: process.env.password,
    port: 22,
    privateKey: fs.readFileSync(__dirname + "/sun_aws.ppk")
  },
  aws: {
    bucket: "cccccc",
    accessKeyId: "cccccc",
    secretAccessKey: "cccccc",
    region: "us-east-1"
  },
  fileDownloadDir: "/home/ubuntu/",
  completedDir: "/completed-uploads/"
};

exports.handler = function(event, context, callback) {
  console.log("config------------->", config.aws);
  SftpToS3.batch(config)
    .then(success => {
      console.log(success);
    })
    .catch(err => {
      console.error(err);
    });
};

I tried to hardcode the bucket value in putbatch function and then it gave timeout error ie.the function cannot run for more than 3 seconds.

**Comment by sunkhanna** [comment]
Also,When I hardcode the bucket name in uploadtos3.js ,it throws the error task timed out after 3 seconds.I am trying to upload a zip file.

**Comment by dhorialpesh** [comment]
I think you need to pass like 'Bucket' instead of bucket. It is case sensitive.
